<a href="https://colab.research.google.com/github/BAgaoglu/tensorflowbeginner/blob/main/tensorbeginner.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.8.0


In [ ]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [ ]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.56507736, -0.6045897 ,  0.42143384,  0.4860555 , -0.5690131 ,
         0.268538  , -0.7280877 ,  0.7771962 , -0.30350417,  0.1722909 ]],
      dtype=float32)

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.05299859, 0.05094533, 0.1421349 , 0.15162317, 0.05279042,
        0.12198289, 0.04502667, 0.20286466, 0.0688437 , 0.11078969]],
      dtype=float32)

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
loss_fn(y_train[:1], predictions).numpy()

2.1038744

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2973 - accuracy: 0.9136
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1449 - accuracy: 0.9570
Epoch 3/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.1084 - accuracy: 0.9671
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0893 - accuracy: 0.9721
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0757 - accuracy: 0.9764


In [ ]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0723 - accuracy: 0.9782 - 506ms/epoch - 2ms/step


[0.07227453589439392, 0.9782000184059143]

In [ ]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [ ]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[4.5001102e-06, 4.3242543e-09, 3.8536058e-05, 4.5423442e-04,
        3.1540423e-11, 2.6397336e-07, 2.2786500e-11, 9.9948835e-01,
        4.3070546e-07, 1.3789367e-05],
       [3.8131991e-09, 4.0603496e-05, 9.9995494e-01, 3.5305482e-06,
        7.9756511e-16, 2.1591431e-07, 4.7064233e-07, 2.3357504e-13,
        2.1090503e-07, 1.5657687e-14],
       [8.3676241e-08, 9.9780291e-01, 5.4557214e-04, 1.8488909e-05,
        4.4531909e-05, 3.1465167e-06, 4.9537666e-05, 1.3161072e-03,
        2.1928427e-04, 3.5509720e-07],
       [9.9993241e-01, 5.5656649e-08, 4.4250446e-05, 3.3911721e-07,
        2.2750906e-09, 1.5138674e-05, 2.9159401e-06, 3.1443776e-07,
        1.6176717e-09, 4.4714598e-06],
       [1.7367840e-05, 5.6968863e-10, 1.9292733e-05, 1.1555800e-07,
        9.9530315e-01, 1.1438215e-06, 7.6347142e-06, 1.1782383e-05,
        8.7185354e-06, 4.6307882e-03]], dtype=float32)>